services:
  postgres:
    image: postgres:16-alpine
    networks:
      - front
    ports:
      - 15432:5432
    volumes:
      - postgresData:/var/lib/postgresql/data
    restart: "no"
    environment:
      POSTGRES_PASSWORD: rootpassword
  redis:
    image: redis:6.2-alpine
    networks:
      - front
    ports:
      - 16379:6379

volumes:
  postgresData:

networks:
  front:
