[[constraint]]
    name = "github.com/kataras/iris"
    version = "11.1.0"

[[constraint]]
    name = "github.com/golang-migrate/migrate/v4"
    version = "4.2.5"

[[constraint]]
    name = "github.com/volatiletech/sqlboiler"
    version = "3.2.0"

[[constraint]]
    name = "github.com/lib/pq"
    version = "1.0.0"