// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package datamodels_raw

var TableNames = struct {
	DomainEmailUser string
	Domains         string
	UserDomain      string
	Users           string
}{
	DomainEmailUser: "domain_email_user",
	Domains:         "domains",
	UserDomain:      "user_domain",
	Users:           "users",
}
