// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package datamodels_raw

var TableNames = struct {
	Domains string
	Users   string
}{
	Domains: "domains",
	Users:   "users",
}
