// Code generated by SQLBoiler 4.12.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package datamodels_raw

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("DomainEmailAliases", testDomainEmailAliasesUpsert)

	t.Run("DomainEmailUsers", testDomainEmailUsersUpsert)

	t.Run("Domains", testDomainsUpsert)

	t.Run("UserDomains", testUserDomainsUpsert)

	t.Run("Users", testUsersUpsert)
}
